#!/usr/bin/bash
# Sets up a local cluster 'cluster-info' on kubernetes using minikube 

# Cleaning up previous attempts if any
minikube delete -p cluster-info --all --purge

echo "🚀 Starting stable single-node cluster..."

minikube start \
    --driver=docker \
    --memory=2500 \
    --cpus=2 \
    --nodes=1 \
    -p cluster-info

# Verifying API server
kubectl cluster-info
kubectl get pods

# Enabling metics + dashboard
minikube addons enable metrics-server dashboard

echo "✅ Cluster ready! Use 'kubectl get pods --all-namespaces'"
